name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  coverage:
    strategy:
      matrix:
        node-version: [16.15.1]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          test-script: npm run test

  pr-labeler:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/config/pr-labeler.yml # optional, .github/ci.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
